repos:
- repo: local
  hooks:
    - id: ruff
      name: ruff
      entry: poetry run ruff check --fix
      require_serial: true
      language: system
      types: [ python ]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      name: black
      language: system
      entry: python -m black
      types: [python]
      args: [--line-length=88, --safe]
